version: "3"

services:
  go-espeak-demo:
    build:
      context: $SERVICESDIR
      dockerfile: $SERVICESDIR/go-espeak-demo/Dockerfile
    command:
      [
        "/app/go-espeak-demo",
        "-port",
        "8080",
        "-audio-dir",
        "/static/audio",
        "-downloads-dir",
        "/static/downloads",
      ]
    environment:
      APPHOST: $APPHOST
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.port=443"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      - "traefik.http.routers.go-espeak-demo.middlewares=https-redirect"
      - "traefik.http.routers.go-espeak-demo.rule=Host(`go-espeak-demo.djangulo.com`)"
      - "traefik.http.routers.go-espeak-demo.entrypoints=web"
      - "traefik.http.routers.go-espeak-demo-tls.rule=Host(`go-espeak-demo.djangulo.com`)"
      - "traefik.http.routers.go-espeak-demo-tls.entrypoints=websecure"
      - "traefik.http.routers.go-espeak-demo-tls.tls=true"
      - "traefik.http.routers.go-espeak-demo-tls.tls.certresolver=leresolver"
