---
resources:
  - name: go-espeak-git
    type: git
    icon: github-circle
    check_every: 10m
    source:
      uri: https://github.com/djangulo/go-espeak.git
      branch: main
      fetch_tags: true
      check: true

  - name: go-espeak-image
    type: docker-image
    icon: docker
    source:
      repository: ((dockerhub/username.username))/go-espeak
      username: ((dockerhub/username.username))
      password: ((dockerhub/password.password))

task-config: &task-config
  platform: linux
  inputs:
    - name: go-espeak-git
  params:
    GO111MODULE: "on"

jobs:
  - name: publish-go-espeak
    plan:
      - get: go-espeak-git
      - put: go-espeak-image
        params:
          build: go-espeak-git/ci/images/go-espeak
  - name: test-unit
    plan:
      - get: go-espeak-git
        trigger: true
        passed: [publish-go-espeak]
      - get: go-espeak-image
      - task: run-tests
        image: go-espeak-image
        config:
          <<: *task-config
          run:
            path: go-espeak-git/ci/task-test.sh
